//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class DignosisTestSaleInfo
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DignosisTestSaleInfo()
        {
            this.DignosisTestSaleReturns = new HashSet<DignosisTestSaleReturn>();
        }
    
        public int Id { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> GenderId { get; set; }
        public Nullable<int> Age { get; set; }
        public Nullable<int> AgeStatusId { get; set; }
        public Nullable<int> Phone { get; set; }
        public Nullable<int> DoctorId { get; set; }
        public Nullable<int> ReferId { get; set; }
        public Nullable<int> DiscountAuthorityId { get; set; }
        public Nullable<int> Total_Cost { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Due { get; set; }
        public Nullable<int> Paid { get; set; }
        public string VAT { get; set; }
        public string BillOfficer { get; set; }
        public Nullable<int> T_Reg { get; set; }
        public Nullable<int> DueCollection { get; set; }
        public Nullable<int> DueDiscount { get; set; }
        public string DueCollectionOfficer { get; set; }
        public Nullable<System.DateTime> DueCollectionDate { get; set; }
        public Nullable<int> DueStatus { get; set; }
        public Nullable<int> ReturnStatus { get; set; }
    
        public virtual AgeStatusInfo AgeStatusInfo { get; set; }
        public virtual DiscountAuthorityInfo DiscountAuthorityInfo { get; set; }
        public virtual DoctorInfo DoctorInfo { get; set; }
        public virtual GenderInfo GenderInfo { get; set; }
        public virtual ReferInfo ReferInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<DignosisTestSaleReturn> DignosisTestSaleReturns { get; set; }
    }
}
