//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserInfo
    {
        public int Id { get; set; }
        public string Username { get; set; }
        public string Password { get; set; }
        public string FastName { get; set; }
        public string LastName { get; set; }
        public Nullable<int> Phone { get; set; }
        public string Permission { get; set; }
        public string Profail { get; set; }
        public string Services { get; set; }
        public string About { get; set; }
        public string Contact { get; set; }
    }
}
