//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class DignosticTestDetail
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DignosticTestDetail()
        {
            this.ReportGenarets = new HashSet<ReportGenaret>();
        }
    
        public int Id { get; set; }
        public string TestName { get; set; }
        public Nullable<int> DepartmentId { get; set; }
        public Nullable<int> CategoryId { get; set; }
        public Nullable<int> SubCategoryId { get; set; }
        public Nullable<int> GroupId { get; set; }
        public Nullable<int> SpecimenId { get; set; }
        public Nullable<int> TestCost { get; set; }
        public Nullable<int> RoomNo { get; set; }
    
        public virtual CategoryInfo CategoryInfo { get; set; }
        public virtual DepartmentInfo DepartmentInfo { get; set; }
        public virtual GroupInfo GroupInfo { get; set; }
        public virtual SpecimenInfo SpecimenInfo { get; set; }
        public virtual SubCategoryInfo SubCategoryInfo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ReportGenaret> ReportGenarets { get; set; }
    }
}
