//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportGenaret
    {
        public int Id { get; set; }
        public Nullable<int> TestId { get; set; }
        public string TestName { get; set; }
        public string Result { get; set; }
        public string Unit { get; set; }
        public string ReferenceValue { get; set; }
    
        public virtual DignosticTestDetail DignosticTestDetail { get; set; }
    }
}
