//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    
    public partial class SP_Day_Wise_Sale_Summary_2_Result1
    {
        public Nullable<System.DateTime> Date { get; set; }
        public string Name { get; set; }
        public string Address { get; set; }
        public Nullable<int> Age { get; set; }
        public string AgeStatus { get; set; }
        public Nullable<int> Phone { get; set; }
        public string D_Name { get; set; }
        public string R_Name { get; set; }
        public string Da_Name { get; set; }
        public Nullable<int> Total_Cost { get; set; }
        public Nullable<int> Discount { get; set; }
        public Nullable<int> Due { get; set; }
        public Nullable<int> Paid { get; set; }
        public string VAT { get; set; }
        public string BillOfficer { get; set; }
        public Nullable<int> DueCollection { get; set; }
        public string DueCollectionOfficer { get; set; }
    }
}
