//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login
{
    using System;
    using System.Collections.Generic;
    
    public partial class StoreTest
    {
        public int S_Id { get; set; }
        public string S_TestName { get; set; }
        public Nullable<int> S_TestPrice { get; set; }
        public Nullable<int> S_RegNumber { get; set; }
        public Nullable<int> TestId { get; set; }
        public Nullable<int> PId { get; set; }
    }
}
